apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: findmyrelative-backend-git-repo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/Meghanaskanagal/findmyrelative-frontend
