apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/find-my-relative/frontend:latest
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: frontend-env

