apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: findmyrelative-backend-cicd-eventlistener
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-findmyrelative-backend-cicd-listener
    weight: 100
